### ISSUE TITLE
Publish to bower

### ISSUE THREAD

**Issue by TSteele27** [azza-bazoo/prettycron#11]
It would be nice to have this package in the bower repository.

**Comment by anderssonjohan** [comment]
I agree :+1:

- Johan
Den 11 jun 2015 03:15 skrev "TSteele27" <notifications@github.com>:

**Comment by anderssonjohan** [comment]
@azza-bazoo: what do you think?

- Johan
Den 11 jun 2015 09:47 skrev "Johan Andersson" <johan.a@remotex.se>:

**Comment by gearsandcode** [comment]
Agreed.

**Comment by azza-bazoo** [comment]
Hi guys! Sorry to be an awful unresponsive maintainer. `bower install prettycron` should now work!

**Comment by anderssonjohan** [comment]
It is so awesome! Great work, we appreciate it! Thanks!


- Johan

**Comment by gearsandcode** [comment]
Awesome! Thanks
