### ISSUE TITLE
Wrong time and day of the week

### ISSUE THREAD

**Issue by s-mahapat** [azza-bazoo/prettycron#23]
The cron 30 10 \* \* 0 which means run at 10:30 every sunday is actually returned as "00:00 on Mon" by getPrettyCron().
## my code:

var cron = "30 10 \* \* 0";
var schedule = later.parse.cron(cron, false);
console.log(getPrettyCron(schedule['schedules'][0]));

**Comment by anderssonjohan** [comment]
@s-mahapat Unfortunately I cannot reproduce the behavior you have described here. Please see test added in #27. I'm closing this issue for now but please let me know if there are reasons to re-open it.
