### ISSUE TITLE
Calendar of next events and timezones

### ISSUE THREAD

**Issue by tsouvarev** [azza-bazoo/prettycron#5]
Say, I've got cron expression "28 4 \* \* \* \* 0" which compiles to "04:28 every day" (that's ok). But when I try to get next events, I get "Tomorrow at 8:28 AM". My timezone is UTC+4, so it's clear, that moment.js detects my locale, and since later.js sets dates in calendar in UTC (adding Z to the end) and all dates shift 4 hours ahead. 
Maybe better choice will be operating on dates like all of them in UTC?

**Comment by pekeler** [comment]
+1

**Comment by marcacyr** [comment]
+1 this is still a bug.

For example, `0 12 * * *` is 12PM every day. It is showing next run as "Tomorrow at 5:00 AM"

**Comment by anderssonjohan** [comment]
Hi all, I will add tests to #14 before merging it. Hopefully I will fix this during the next week (and I mean next week as in local time ;)).

(Sorry for the late response)

**Comment by appinteractive** [comment]
@anderssonjohan hey what is the status? Any progress?

**Comment by anderssonjohan** [comment]
@appinteractive Sorry, actually not :( This project has unfortunately moved down on my list of prioritizations for a long time. I will try to find the hours needed since you obviously are waiting for it :)

**Comment by appinteractive** [comment]
@anderssonjohan thanks, we solved that issue already by implementing that method ourself. But would still be nice if you would solve that issue in your library directly so everyone can participate :)

I think merging #14 should solve that issue. 

Thanks by the way for sharing your library 👍

**Comment by parichayBatra** [comment]
@appinteractive how did you solve the issue?

**Comment by appinteractive** [comment]
@parichayBatra we overwrote the method above and fixed it with it by then. As I mentioned the pull request #14 should have fixed it. Can't text it as I do not have access to the sources of that project anymore.
